name: Auto Flat ZIP + Tests

on:
  workflow_dispatch:
  release:
    types: [released, prereleased, edited]
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  test_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ShellCheck
        run: find . -name "*.sh" -print0 | xargs -0 shellcheck -e SC2148

  attach-zip-and-notify:
    needs: test_code
    if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo "TIMESTAMP=$(date +'%Y.%m.%d-%H%M')" >> $GITHUB_ENV
          echo "ZIP_FILE=SoundATMOSphere-1.55-Stable.zip" >> $GITHUB_ENV

      - name: Create clean flat ZIP
        run: zip -r "${{ env.ZIP_FILE }}" . -x ".git/*" -x ".github/*" -x ".*"

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ZIP_FILE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Telegram message for Release
        if: github.event_name == 'release'
        run: echo "MSG=🚀 New Release Available! 📦 Version: ${{ github.event.release.tag_name }} ⏰ Time: ${{ env.TIMESTAMP }}" >> $GITHUB_ENV

      - name: Telegram message for Manual run
        if: github.event_name == 'workflow_dispatch'
        run: echo "MSG=🔧 Manual Build Triggered 📦 Version: 1.55 Stable ⏰ Time: ${{ env.TIMESTAMP }}" >> $GITHUB_ENV

      - name: Send File to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          document: ${{ env.ZIP_FILE }}
          message: ${{ env.MSG }}

